In [1]:
import pandas as pd
import numpy as np
import pickle
import sys
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.stem.porter import *
import string
import re
#from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer as VS
from textstat.textstat import *
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import classification_report
from sklearn.svm import LinearSVC
import matplotlib.pyplot as plt
import seaborn
%matplotlib inline

ModuleNotFoundError: No module named 'textstat'

## Tweets

In [4]:
import pandas as pd

df = pd.read_csv('./data/hate-speed/haspeede_TW-train.tsv',sep='\t', names=['ID','Text','Label'])
df

ID                                               Text  \
0     576268275560116224  @matteorenzi ...all'invasione di questi animal...   
1     815833978691260416  È terrorismo anche questo, per mettere in uno ...   
2     815112299044372480  @Nanoalto @FedeAngeli infatti finché ci hanno ...   
3     577451440047853568  @dinofarnesi Piovegovernolad    In  Italia   a...   
4     844921803575382016  #londonattack chiedete ai buonisti del cavolo ...   
5     811099342593462272  Corriere: Tangenti, Mafia Capitale dimenticata...   
6     833323806873833473  @Pontifex_it ad uno ad uno, perché quando i mi...   
7     835493194796314624  Il divertimento del giorno? Trovare i patrioti...   
8     839605324684361730  Modena: Comune paga la benzina ai nomadi che p...   
9     851906322283016192  @Cartabiancarai3 @KhalidChaouki3 altro che isl...   
10    834785125258911744  @FaenzaStefano @1974_sim74 @repubblicait grazi...   
11    782928453872062464  Mons. Liberati: “In 10 anni l’Europa sarà isla...   
12    821056358283902977  @investigator113 altro che profughi? sono zavo...   
13    783280663365574656  @lilly0971 ne ho piene le palle!!!il giorno de...   
14    818135548489515009  ... e smettetela di dire che anche gli italian...   
15    826013678726160385  Le responsabilità della crisi economica, di va...   
16    835894111928528896  @iosonokarma la mia non e' cattiveria ma dirit...   
17    848835878969540612  Minorenne rom arrestato dopo furto in appartam...   
18    810120475074555908  Studentessa cinese morta fermato un nomade di ...   
19    578609578423808000  @Sen_Pedica Stefano è ora che l' italia cominc...   
20    835948142122127360  Ddl di Calderoli: “Il velo islamico e l’apolog...   
21    824571157269639168  Roma, rapina al campo rom La Barbuta: tre arre...   
22    826378364827099136  Rischiando di essere presa per pazza che non s...   
23    792613642533539840  @ClaudioDeglinn2 @italodisco1975 a proposito d...   
24    801383022608191488  Povertà, esclusione e scarsa istruzione: "4100...   
25    826202983004246016  #Roma #Torino, grazie al collegamento con i ca...   
26    854427382039683072  Floris presentatore senza spina dorsale dovres...   
27    822158606632124417  @ondaquadra @spartachisti lo zucchero te lo da...   
28    799650731779358720  #profughi   ....e ci sono ancora dei malvedent...   
29    848953272941637636  Sarà un caso che è stata colpita la città + "o...   
...                  ...                                                ...   
2968  827614048992784384  #Niger Il risultato degli accordi anti-migrant...   
2969  784623293445922816  Arrigoni al centro migranti di Cremeno: quasi ...   
2970  816217760187486209  La furia violenta degli islamici arriva anche ...   
2971  821115711175225345  #QuintaColonna gli islamici sono la peste del ...   
2972  551988544361988096  Complimenti agli islamici x aver relegato le d...   
2973  786329124273057800  Essere musulmani a Roma: Dove andare a pregare...   
2974  823657132151214080  #Presadiretta Mi auguro che le stesse torture ...   
2975  563464340851130370  Un bella testata al Plutonio, e a chi tocca to...   
2976  789137844967137280  Il Prefetto di Arezzo visita Castelfranco – Pi...   
2977  825408756376858624  Italia ridicola che fa parlare rom che devasta...   
2978  831536055820095488  @MauroLumini Abbiamo di tutto di + anche finti...   
2979  840850479093600256  Emma Bonino alla convention del Lingotto: “Sen...   
2980  824998697935175682  Roma: arrestati cinque ladri rom acrobati, men...   
2981  840228788755652608  Non solo #turisti. Gli stranieri amano l’Itali...   
2982  845159172169617408  Roma, scatta l’allerta terrorismo ma fanno più...   
2983  830437603442884610  @AlessiaMorani Abbiamo l'Italia piena di cland...   
2984  815170234202148865  Stretta sul terrorismo: maggiori controlli e a...   
2985  590261842469072899  Giornalisti sciacalli di tutta Italia, vi sto ...   
2986  821719461409517568  @enricovik @tantosec62 Facebook è dell'ebreo Z

## STOPWORDS

In [4]:
from string import punctuation
import pandas as pd
#from gensim.parsing.preprocessing import STOPWORDS

print("GENSIM")
print("Len")
#len(STOPWORDS)

print("EVALITA")
pd.read_csv('./data/stopwords/IT-EVALITA16-stopwords.txt')

print("ISO")
pd.read_csv('./data/stopwords/IT-stopwordsISO-stopwords.txt')

GENSIM
Len
EVALITA
ISO


a
0    abbastanza
1         abbia
2       abbiamo
3       abbiano
4       abbiate
5     accidenti
6            ad
7        adesso
8      affinche
9           agl
10         agli
11        ahime
12       ahimã¨
13        ahimè
14           ai
15           al
16       alcuna
17       alcuni
18       alcuno
19          all
20         alla
21         alle
22         allo
23       allora
24        altre
25        altri
26   altrimenti
27        altro
28      altrove
29       altrui
..          ...
629       tutto
630      uguali
631   ulteriore
632      ultimo
633          un
634         una
635         uno
636        uomo
637          va
638         vai
639        vale
640        vari
641       varia
642       varie
643       vario
644       verso
645          vi
646         via
647      vicino
648       visto
649        vita
650         voi
651       volta
652       volte
653      vostra
654      vostre
655      vostri
656      vostro
657          ã¨
658           è

[659 rows x 1 columns]

# word2vec visualization

In [1]:
def tsne_plot(model):
    "Creates and TSNE model and plots it"
    labels = []
    tokens = []

    for word in model.wv.vocab:
        tokens.append(model[word])
        labels.append(word)
    
    tsne_model = TSNE(perplexity=40, n_components=2, init='pca', n_iter=2500, random_state=23)
    new_values = tsne_model.fit_transform(tokens)

    x = []
    y = []
    for value in new_values:
        x.append(value[0])
        y.append(value[1])
        
    plt.figure(figsize=(16, 16)) 
    for i in range(len(x)):
        plt.scatter(x[i],y[i])
        plt.annotate(labels[i],
                     xy=(x[i], y[i]),
                     xytext=(5, 2),
                     textcoords='offset points',
                     ha='right',
                     va='bottom')
    plt.show()

In [5]:
import gensim

word2vec_model = gensim.models.Word2Vec.load("data/word2vec/glove_WIKI")




In [7]:
from sklearn.manifold import TSNE

tsne_plot(word2vec_model)

/home/thenhz/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  import sys


MemoryError: 

In [109]:
import numpy as np

y = np.random.randint(0,2,3)
print(y)
a = np.int8(np.logical_not(y))
print(a)
np.vstack((y,a)).T

[1 1 0]
[0 0 1]


array([[1, 0],
       [1, 0],
       [0, 1]])